Corrected return statuses

diff --git a/ShellPlugins/Bell_Alarm b/ShellPlugins/Bell_Alarm
--- a/ShellPlugins/Bell_Alarm
+++ b/ShellPlugins/Bell_Alarm
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Bell_Alarm
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Sat 16 Sep 18:23:16 BST 2017
+# Last Change       - Mon 25 Sep 18:59:45 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -11,7 +11,7 @@
 bell()
 {
 	# Load error functions.
-	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
 	ERR(){ echo "ERROR: $1" 1>&2; }
 	
 	# Check for root access.
@@ -29,7 +29,7 @@ bell()
 	}
 	
 	# Return if any dependencies are unmet.
-	[ $DEPCOUNT -eq 0 ] || return
+	[ $DEPCOUNT -eq 0 ] || return 1
 
 	# If the module-x11-bell pactl module is loaded, continue.
 	if /usr/bin/pactl list modules | /bin/grep -q "module-x11-bell"
@@ -41,9 +41,9 @@ bell()
 			/bin/sleep 1
 		done
 	else
-		# If module not loaded, output error and return.
+		# If module not loaded, output error and return 1.
 		echo "ERROR: PulseAudio needs 'module-x11-bell' loaded." 1>&2
 		echo "       Execute 'pactl list modules' to double-check." 1>&2
-		return
+		return 1
 	fi
 }
diff --git a/ShellPlugins/CPU_Intensive_Procs b/ShellPlugins/CPU_Intensive_Procs
--- a/ShellPlugins/CPU_Intensive_Procs
+++ b/ShellPlugins/CPU_Intensive_Procs
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/CPU_Intensive_Procs
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Fri 15 Sep 14:58:15 BST 2017
+# Last Change       - Mon 25 Sep 19:01:54 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -14,10 +14,10 @@ cpuhit()
 	|| ( [ "$1" -lt 1 ] || [ "$1" -gt 10 ] )
 	then
 		echo "USAGE: cpuhit [1-10]" 1>&2
-		return
+		return 1
 	fi
 
-	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
 	ERR(){ echo "ERROR: $1" 1>&2; }
 	
 	[ $UID -eq 0 ] && RERR "Root access isn't required."
@@ -32,7 +32,7 @@ cpuhit()
 		fi
 	}
 	
-	[ $DEPCOUNT -eq 0 ] || return
+	[ $DEPCOUNT -eq 0 ] || return 1
 
 	/bin/ps -eo pcpu,pid\
 		| /usr/bin/sort -k 1 -rn\
diff --git a/ShellPlugins/Clear_CD_LS b/ShellPlugins/Clear_CD_LS
--- a/ShellPlugins/Clear_CD_LS
+++ b/ShellPlugins/Clear_CD_LS
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/CD_Clear_LS
 # Started On        - Thu 14 Sep 20:15:25 BST 2017
-# Last Change       - Sat 16 Sep 18:23:11 BST 2017
+# Last Change       - Mon 25 Sep 19:01:41 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -13,6 +13,8 @@
 
 cd()
 {
+	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
+
 	# Continue if /bin/ls is found -- because you never know when.
 	if type /bin/ls &> /dev/null
 	then
@@ -31,7 +33,6 @@ cd()
 		fi
 	else
 		# If /bin/ls is not found, say so and return.
-		echo "ERROR: Dependency '/bin/ls' not met." 1>&2
-		return
+		RERR "Dependency '/bin/ls' not met."
 	fi
 }
diff --git a/ShellPlugins/Create_VM b/ShellPlugins/Create_VM
--- a/ShellPlugins/Create_VM
+++ b/ShellPlugins/Create_VM
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Create_VM
 # Started On        - Thu 14 Sep 20:16:42 BST 2017
-# Last Change       - Sat 16 Sep 18:23:07 BST 2017
+# Last Change       - Mon 25 Sep 19:02:06 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -14,7 +14,7 @@
 mkvm()
 {
 	# Load error functions.
-	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
 	ERR(){ echo "ERROR: $1" 1>&2; }
 
 	# Check for root access.
@@ -24,7 +24,7 @@ mkvm()
 	if ! type -P "$DEP" &> /dev/null
 	then
 		ERR "Dependency '/usr/bin/vboxmanage' not met."
-		return
+		return 1
 	fi
 
 	# Output error if number of arguments don't equal 2.
diff --git a/ShellPlugins/Get_Bad_Hosts b/ShellPlugins/Get_Bad_Hosts
--- a/ShellPlugins/Get_Bad_Hosts
+++ b/ShellPlugins/Get_Bad_Hosts
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Get_Bad_Hosts
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Fri 15 Sep 15:07:51 BST 2017
+# Last Change       - Mon 25 Sep 18:58:53 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -12,7 +12,7 @@
 
 gbh()
 {
-	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
 	ERR(){ echo "ERROR: $1" 1>&2; }
 	
 	[ $UID -eq 0 ] && RERR "Root access isn't required."
@@ -27,7 +27,7 @@ gbh()
 		fi
 	}
 	
-	[ $DEPCOUNT -eq 0 ] || return
+	[ $DEPCOUNT -eq 0 ] || return 1
 
 	if ! [ $# -eq 0 ]
 	then
@@ -57,5 +57,4 @@ gbh()
 		| /usr/bin/sort\
 		| /bin/gzip -c\
 		> "$DESTINATION"
-
 }
diff --git a/ShellPlugins/List_Signals b/ShellPlugins/List_Signals
--- a/ShellPlugins/List_Signals
+++ b/ShellPlugins/List_Signals
@@ -3,14 +3,14 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/List_Signals
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Fri 15 Sep 15:09:56 BST 2017
+# Last Change       - Mon 25 Sep 19:02:38 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 lssig()
 {
-	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
 	ERR(){ echo "ERROR: $1" 1>&2; }
 
 	[ $UID -eq 0 ] && RERR "Root access isn't required."
@@ -32,6 +32,6 @@ lssig()
 		} | /usr/bin/column -x
 	else
 		echo "ERROR: Dependency '/usr/bin/column' not met." 1>&2
-		return
+		return 1
 	fi
 }
