Cleaned and updated plugins

diff --git a/ShellPlugins/Bell_Alarm b/ShellPlugins/Bell_Alarm
--- a/ShellPlugins/Bell_Alarm
+++ b/ShellPlugins/Bell_Alarm
@@ -1,35 +1,42 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/Bell_Alarm
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 14:51:49 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 bell()
 {
-	if [ $UID -eq 0 ]
-	then
-		echo "ERROR: Root access is not required." 1>&2
-		exit 1
-	fi
-
-	if [ $# -gt 0 ]
-	then
-		echo "ERROR: No arguments are required." 1>&2
-		exit 1
-	fi
-
-	if type -P /usr/bin/pactl /bin/{sleep,grep} &> /dev/null
-	then
-		if /usr/bin/pactl list modules | /bin/grep -q "module-x11-bell"
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	ERR(){ echo "ERROR: $1" 1>&2; }
+	
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	
+	DEPCOUNT=0
+	for DEP in /usr/bin/pactl /bin/{grep,sleep}
+	{
+		if ! type -P "$DEP" &> /dev/null
 		then
-			while :
-			do
-				printf "\a"
-				/bin/sleep 1
-			done
-		else
-			echo "ERROR: PulseAudio needs 'module-x11-bell' loaded." 1>&2
-			echo "       Execute 'pactl list modules' to double-check." 1>&2
-			exit 1
+			ERR "Dependency '$DEP' not met."
+			let DEPCOUNT++
 		fi
+	}
+	
+	[ $DEPCOUNT -eq 0 ] || return
+
+	if /usr/bin/pactl list modules | /bin/grep -q "module-x11-bell"
+	then
+		while :
+		do
+			printf "\a"
+			/bin/sleep 1
+		done
 	else
-		echo "ERROR: Cannot find 'pactl'; is PulseAudio installed?" 1>&2
+		echo "ERROR: PulseAudio needs 'module-x11-bell' loaded." 1>&2
+		echo "       Execute 'pactl list modules' to double-check." 1>&2
+		return
 	fi
 }
diff --git a/ShellPlugins/CPU_Intensive_Procs b/ShellPlugins/CPU_Intensive_Procs
--- a/ShellPlugins/CPU_Intensive_Procs
+++ b/ShellPlugins/CPU_Intensive_Procs
@@ -1,21 +1,40 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/CPU_Intensive_Procs
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 14:58:15 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 cpuhit()
 {
-	if [ $# -eq 0 ] || [ $# -gt 1 ]
+	if ( [ $# -eq 0 ] || [ $# -gt 1 ] )\
+	|| ( [ "$1" -lt 1 ] || [ "$1" -gt 10 ] )
 	then
 		echo "USAGE: cpuhit [1-10]" 1>&2
 		return
 	fi
 
-	if [ "$1" -lt 1 ] || [ "$1" -gt 10 ]
-	then
-		echo "Argument '$1' is out of the 1 to 10 range." 1>&2
-		return
-	fi
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	ERR(){ echo "ERROR: $1" 1>&2; }
+	
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	
+	DEPCOUNT=0
+	for DEP in /usr/bin/{awk,sort} /bin/ps
+	{
+		if ! type -P "$DEP" &> /dev/null
+		then
+			ERR "Dependency '$DEP' not met."
+			let DEPCOUNT++
+		fi
+	}
+	
+	[ $DEPCOUNT -eq 0 ] || return
 
-	ps -eo pcpu,pid\
+	/bin/ps -eo pcpu,pid\
 		| /usr/bin/sort -k 1 -rn\
 		| /usr/bin/awk -Sv var=$1 'NR==1,NR==var {print $1"%","("$2")"}'
 }
diff --git a/ShellPlugins/Cleaner_RK_Scan b/ShellPlugins/Cleaner_RK_Scan
--- a/ShellPlugins/Cleaner_RK_Scan
+++ b/ShellPlugins/Cleaner_RK_Scan
@@ -1,15 +1,33 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/Cleaner_RK_Scan
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 14:52:30 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 rkc()
 {
-	if [ $UID -eq 0 ]
-	then
-		echo "ERROR: Do not run as root!" 1>&2
-		return
-	fi
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	ERR(){ echo "ERROR: $1" 1>&2; }
+	
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	
+	DEPCOUNT=0
+	for DEP in /usr/bin/rkhunter /bin/sed /sbin/chkrootkit
+	{
+		if ! type -P "$DEP" &> /dev/null
+		then
+			ERR "Dependency '$DEP' not met."
+			let DEPCOUNT++
+		fi
+	}
+	
+	[ $DEPCOUNT -eq 0 ] || return
 
-	/usr/bin/sudo /usr/bin/rkhunter -c --skip-keypress --rwo
+	/usr/bin/rkhunter -c --skip-keypress --rwo
 
 	/bin/sed '
 		/nothing found/d;
@@ -19,5 +37,5 @@ rkc()
 		/nothing deleted/d;
 		/no suspect files/d;
 		/no such file or directory/d
-	' <<< "$(/usr/bin/sudo /usr/sbin/chkrootkit)"
+	' <<< "$(/usr/sbin/chkrootkit)"
 }
diff --git a/ShellPlugins/Clear_CD_LS b/ShellPlugins/Clear_CD_LS
--- a/ShellPlugins/Clear_CD_LS
+++ b/ShellPlugins/Clear_CD_LS
@@ -1,18 +1,29 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
 
-# Clears the terminal before executing cd and then ls. Skip with \cd.
-# Limited function, but useful. May revisit at a later date.
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/CD_Clear_LS
+# Started On        - Thu 14 Sep 20:15:25 BST 2017
+# Last Change       - Fri 15 Sep 14:54:44 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
+
 cd()
 {
-	if [ $# -eq 0 ]
-        then
-		echo -ne "\033c"
-		cd "$HOME"
-		ls
+	if type -P /bin/ls &> /dev/null
+	then
+		if [ $# -eq 0 ]
+        	then
+			printf "\033c"
+			cd "$HOME"
+			/bin/ls
+		else
+			printf "\033c"
+			cd "$*"
+			/bin/ls
+		fi
 	else
-		echo -ne "\033c"
-		cd "$*"
-		ls
+		echo "ERROR: Dependency '/bin/ls' not met." 1>&2
+		return
 	fi
 }
diff --git a/ShellPlugins/Create_VM b/ShellPlugins/Create_VM
--- a/ShellPlugins/Create_VM
+++ b/ShellPlugins/Create_VM
@@ -1,39 +1,37 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/Create_VM
+# Started On        - Thu 14 Sep 20:16:42 BST 2017
+# Last Change       - Fri 15 Sep 15:01:40 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 # $1 = Name
 # $2 = Type
 
 mkvm()
 {
-	FAULT_COUNT=0
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
 	ERR(){ echo "ERROR: $1" 1>&2; }
 
-	if [ $UID -eq 0 ]
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	
+	if ! type -P "$DEP" &> /dev/null
 	then
-		ERR "Root access not recommended."
-		let FAULT_COUNT++
-	fi
-
-	if ! type -P /usr/bin/vboxmanage &> /dev/null
-	then
-		ERR "Dependency 'vboxmanage' not met."
-		let FAULT_COUNT++
+		ERR "Dependency '/usr/bin/vboxmanage' not met."
+		return
 	fi
 
 	if ! [ $# -eq 2 ]
-	then
-		ERR "Correct syntax is 'mkvm <name> <ostype>'." 1>&2
-		let FAULT_COUNT++
+		RERR "Correct syntax is 'mkvm <name> <ostype>'."
 	fi
 
 	if [ -z "$VBOX_USER_HOME" ]
 	then
-		ERR "Environment variable 'VBOX_USER_HOME' not set."
-		let FAULT_COUNT++
+		RERR "Environment variable 'VBOX_USER_HOME' not set."
 	fi
-
-	[ $FAULT_COUNT -gt 0 ] && return
 	
 	(
 		echo "Creating and registering the virtual machine."
diff --git a/ShellPlugins/Get_Bad_Hosts b/ShellPlugins/Get_Bad_Hosts
--- a/ShellPlugins/Get_Bad_Hosts
+++ b/ShellPlugins/Get_Bad_Hosts
@@ -1,42 +1,50 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/Get_Bad_Hosts
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 15:07:51 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 # WORK IN PROGRESS
 
 gbh()
 {
-	if [ $UID -eq 0 ]
-	then
-		echo "ERROR: Don't run as root!" 1>&2
-		return
-	fi
-
-	if ! [ $# -eq 0 ]
-	then
-		echo "ERROR: No arguments required." 1>&2
-		return
-	fi
-
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	ERR(){ echo "ERROR: $1" 1>&2; }
+	
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	
 	DEPCOUNT=0
-	for DEP in /bin/{grep,gzip} /usr/bin/{wget,dos2unix,uniq,sort,tr}
+	for DEP in /bin/{cat,grep,gzip} /usr/bin/{wget,dos2unix,uniq,sort,tr}
 	{
 		if ! type -P "$DEP" &> /dev/null
 		then
-			echo "ERROR: Dependency '$DEP' not met." 1>&2
+			ERR "Dependency '$DEP' not met."
 			let DEPCOUNT++
 		fi
 	}
-
+	
 	[ $DEPCOUNT -eq 0 ] || return
+
+	if ! [ $# -eq 0 ]
+	then
+		RERR "ERROR: No arguments required."
+	fi
 
 	URL="http://www.montanamenagerie.org/hostsfile/hosts.txt"
 	DESTINATION="$HOME/Downloads/GBH.txt"
-	[ -d "${DESTINATION%\/*}" ] || return
+
+	if ! [ -d "${DESTINATION%\/*}" ]
+	then
+		RERR "Destination directory not found."
+	fi
 
 	if [ -f "${DESTINATION}.gz" ]
 	then
-		echo "ERROR: File already present." 1>&2
-		return
+		RERR "ERROR: File already present."
 	fi
 
 	/usr/bin/wget -q --show-progress "$URL" -O "$DESTINATION"
@@ -47,7 +55,7 @@ gbh()
 		| /bin/grep -a "^127.0.0.1 "\
 		| /usr/bin/uniq\
 		| /usr/bin/sort\
-		| /usr/bin/gzip -c\
+		| /bin/gzip -c\
 		> "$DESTINATION"
 
 }
diff --git a/ShellPlugins/List_Signals b/ShellPlugins/List_Signals
--- a/ShellPlugins/List_Signals
+++ b/ShellPlugins/List_Signals
@@ -1,19 +1,20 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/List_Signals
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 15:09:56 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 lssig()
 {
-	if [ $UID -eq 0 ]
-	then
-		echo "ERROR: Root access is not required." 1>&2
-		exit 1
-	fi
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
+	ERR(){ echo "ERROR: $1" 1>&2; }
 
-	if [ $# -gt 0 ]
-	then
-		echo "ERROR: No arguments are required." 1>&2
-		exit 1
-	fi
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	[ $# -gt 0 ] || RERR "No arguments are required."
 
 	if type -P /usr/bin/column &> /dev/null
 	then
@@ -30,7 +31,7 @@ lssig()
 			printf "%2d %s\n" "${NUM%:*}" "${SIG/*:}"
 		} | /usr/bin/column -x
 	else
-		echo "ERROR: Dependency 'column' and 'printf' required." 1>&2
+		echo "ERROR: Dependency '/usr/bin/column' not met." 1>&2
 		return
 	fi
 }
diff --git a/ShellPlugins/Load_File_Links2 b/ShellPlugins/Load_File_Links2
--- a/ShellPlugins/Load_File_Links2
+++ b/ShellPlugins/Load_File_Links2
@@ -1,28 +1,24 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/Load_File_Links2
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 15:12:29 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 l2f()
 {
-	if [ $# -eq 0 ]
-	then
-		echo "ERROR: Please specify a file to be read." 1>&2
-		return
-	fi
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
 
-	if [ $UID -eq 0 ]
-	then
-		echo "ERROR: Root access is not recommended here." 1>&2
-		return
-	fi
-	
+	[ $UID -eq 0 ] && RERR "Root access isn't recommended."
+	[ $# -gt 0 ] || RERR "Please specify a file to be read."
+
 	if type -P /usr/bin/links2 &> /dev/null
 	then
 		/usr/bin/links2 -force-html file://"$@"
-	elif type -P /usr/bin/links &> /dev/null
-	then
-		/usr/bin/links -force-html file://"$@"
 	else
-		echo "ERROR: Program 'links2' or 'links' not found." 1>&2
-		return
+		RERR "Dependency '/usr/bin/links2' not found."
 	fi
 }
diff --git a/ShellPlugins/NIR_Difference b/ShellPlugins/NIR_Difference
--- a/ShellPlugins/NIR_Difference
+++ b/ShellPlugins/NIR_Difference
@@ -1,17 +1,36 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
+
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/NIR_Difference
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 15:15:32 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
 
 nirdiff()
 {
-        RERR(){ echo "ERROR: $1" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
 
-        if [ ! "$#" -eq "1" ]
-	then
-		RERR "One argument (package name) is required."
-        elif dpkg-query --status "$1" &> /dev/null
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	[ $# -gt 1 ] || RERR "Please specify a package name."
+
+	DEPCOUNT=0
+	for DEP in /usr/bin/{apt-get,awk,dpkg-query}
+	{
+		if ! type -P "$DEP" &> /dev/null
+		then
+			ERR "Dependency '$DEP' not met."
+			let DEPCOUNT++
+		fi
+	}
+	
+	[ $DEPCOUNT -eq 0 ] || exit 1
+
+        if /usr/bin/dpkg-query --status "$1" &> /dev/null
 	then
 		RERR "Package already installed."
-        elif ! dpkg-query --show "$1" &> /dev/null
+        elif ! /usr/bin/dpkg-query --show "$1" &> /dev/null
 	then
 		RERR "Package '$1' not found."
 	fi
@@ -21,7 +40,7 @@ nirdiff()
         for SIM in "--no-" "--"
         {
 		/usr/bin/apt-get install -s ${SIM}install-recommends "$1" 2> /dev/null\
-			| /usr/bin/awk -v SIM="$SIM" '
+			| /usr/bin/awk -Sv SIM="$SIM" '
 				{
 					if(/^[0-9]+ to upgrade,\s/)
 						printf "%-25s%10d\n",SIM"install-recommends",$4
diff --git a/ShellPlugins/Play_Download_MPSYT b/ShellPlugins/Play_Download_MPSYT
--- a/ShellPlugins/Play_Download_MPSYT
+++ b/ShellPlugins/Play_Download_MPSYT
@@ -1,31 +1,43 @@
 #!/bin/bash
-# Written by terminalforlife (terminalforlife@yahoo.com)
 
-if type -P /usr/bin/mpsyt &> /dev/null
-then
-	yt()
+#----------------------------------------------------------------------------------
+# Project Name      - $HOME/ShellPlugins/Play_Download_MPSYT
+# Started On        - Thu 14 Sep 20:10:21 BST 2017
+# Last Change       - Fri 15 Sep 15:20:04 BST 2017
+# Author E-Mail     - terminalforlife@yahoo.com
+# Author GitHub     - https://github.com/terminalforlife
+#----------------------------------------------------------------------------------
+
+yt()
+{
+	ARG_FAIL(){ echo "USAGE: yt [-p|-d] URL" 1>&2; return; }
+	RERR(){ echo "ERROR: $1" 1>&2; return; }
+
+	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	[ $# -gt 1 ] || RERR "Please specify a package name."
+
+	DEPCOUNT=0
+	for DEP in /usr/bin/{apt-get,awk,dpkg-query}
 	{
-		if [ $# -gt 2 ]
+		if ! type -P "$DEP" &> /dev/null
 		then
-			echo "USAGE: yt [-p|-d] URL"
-			return
-		fi
-
-		if [ $UID -eq 0 ]
-		then
-			echo "ERROR: Root access is not required."
-			return
-		fi
-	
-		if [ "$1" == "-p" ]
-		then
-			/usr/bin/mpsyt playurl "$2"
-		elif [ "$1" == "-d" ]
-		then
-			/usr/bin/mpsyt dlurl "$2"
-		else
-			echo "Error."
-			return
+			ERR "Dependency '$DEP' not met."
+			let DEPCOUNT++
 		fi
 	}
-fi
+	
+	[ $DEPCOUNT -eq 0 ] || exit 1
+
+	if [ $# -gt 2 ]
+	then
+		ARG_FAIL
+	elif [ "$1" == "-p" ]
+	then
+		/usr/bin/mpsyt playurl "$2"
+	elif [ "$1" == "-d" ]
+	then
+		/usr/bin/mpsyt dlurl "$2"
+	else
+		ARG_FAIL
+	fi
+}
