Updated

diff --git a/ShellPlugins/Bell_Alarm b/ShellPlugins/Bell_Alarm
--- a/ShellPlugins/Bell_Alarm
+++ b/ShellPlugins/Bell_Alarm
@@ -3,24 +3,24 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Bell_Alarm
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Tue  3 Oct 18:20:17 BST 2017
+# Last Change       - Thu  5 Oct 18:02:27 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 bell(){
 	# Load error functions.
-	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
-	ERR(){ echo "ERROR: $1" 1>&2; }
+	RERR(){ echo "[L${1}] ERROR: $2" 1>&2; return 1; }
+	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
 	
 	# Check for root access.
-	[ $UID -eq 0 ] && RERR "Root access isn't required."
+	[ $UID -eq 0 ] && RERR "$LINENO" "Root access isn't required."
 	
 	# Check for dependencies.
 	declare -i DEPCOUNT=0
 	for DEP in /usr/bin/pactl /bin/{grep,sleep}; {
 		[ -x "$DEP" ] || {
-			ERR "Dependency '$DEP' not met."
+			ERR "$LINENO" "Dependency '$DEP' not met."
 			DEPCOUNT+=1
 		}
 	}
@@ -31,15 +31,12 @@ bell(){
 	# If the module-x11-bell pactl module is loaded, continue.
 	/usr/bin/pactl list modules | /bin/grep -q "module-x11-bell" && {
 		# Infinitely sound the bell every second.
-		while :
-		do
+		while :; do
 			printf "\a"
 			/bin/sleep 1
 		done
 	} || {
 		# If module not loaded, output error and return 1.
-		echo "ERROR: PulseAudio needs 'module-x11-bell' loaded." 1>&2
-		echo "       Execute 'pactl list modules' to double-check." 1>&2
-		return 1
+		XERR "$LINENO" "ERROR: PulseAudio needs 'module-x11-bell' loaded."
 	}
 }
diff --git a/ShellPlugins/CPU_Intensive_Procs b/ShellPlugins/CPU_Intensive_Procs
--- a/ShellPlugins/CPU_Intensive_Procs
+++ b/ShellPlugins/CPU_Intensive_Procs
@@ -3,23 +3,23 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/CPU_Intensive_Procs
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Tue  3 Oct 18:20:04 BST 2017
+# Last Change       - Thu  5 Oct 18:05:47 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 cpuhit(){
-	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
+	RERR(){ echo "[L${1}] ERROR: $2" 1>&2; return 1; }
 
 	[ -x /bin/ps ] && {
-		RERR "Dependency '/bin/ps' not met." || return 1
+		RERR "$LINENO" "Dependency '/bin/ps' not met." || return 1
 	}
 
 	case "${*:-EMPTY}" in
 		[1-9]|10)
 			;;
 		*)
-			RERR "USAGE: cpuhit [1-10]" || return 1 ;;
+			RERR "$LINENO" "USAGE: cpuhit [1-10]" || return 1 ;;
 	esac
 
 	local IFS=" "
diff --git a/ShellPlugins/NIR_Difference b/ShellPlugins/NIR_Difference
--- a/ShellPlugins/NIR_Difference
+++ b/ShellPlugins/NIR_Difference
@@ -3,21 +3,21 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/NIR_Difference
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Tue  3 Oct 18:31:04 BST 2017
+# Last Change       - Thu  5 Oct 18:09:03 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 nirdiff(){
-	RERR(){ echo "ERROR: $1" 1>&2; return 1; }
+	RERR(){ echo "[L${1}] ERROR: $2" 1>&2; return 1; }
 
-	[ $UID -eq 0 ] && RERR "Root access isn't required."
-	[ $# -gt 1 ] || RERR "Please specify a package name."
+	[ $UID -eq 0 ] && RERR "$LINENO" "Root access isn't required."
+	[ $# -gt 1 ] || RERR "$LINENO" "Please specify a package name."
 
 	declare -i DEPCOUNT=0
 	for DEP in /usr/bin/{apt-get,awk,dpkg-query}; {
 		[ -x "$DEP" ] || {
-			ERR "Dependency '$DEP' not met."
+			ERR "$LINENO" "Dependency '$DEP' not met."
 			DEPCOUNT+=1
 		}
 	}
@@ -25,9 +25,9 @@ nirdiff(){
 	[ $DEPCOUNT -eq 0 ] || exit 1
 
 	if /usr/bin/dpkg-query --status "$1" &> /dev/null; then
-		RERR "Package already installed."
+		RERR "$LINENO" "Package already installed."
 	elif ! /usr/bin/dpkg-query --show "$1" &> /dev/null; then
-		RERR "Package '$1' not found."
+		RERR "$LINENO" "Package '$1' not found."
 	fi
 
 	printf "%-25s%10s\n" "FLAG" "PKG"
