Updated ShellPlugins/Get_Bad_Hosts

diff --git a/ShellPlugins/Get_Bad_Hosts b/ShellPlugins/Get_Bad_Hosts
--- a/ShellPlugins/Get_Bad_Hosts
+++ b/ShellPlugins/Get_Bad_Hosts
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Get_Bad_Hosts
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Thu  5 Oct 18:08:07 BST 2017
+# Last Change       - Fri 13 Oct 23:47:29 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -11,14 +11,14 @@
 # WORK IN PROGRESS
 
 gbh(){
-	RERR(){ echo "[L${1}] ERROR: $2" 1>&2; return 1; }
 	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
 	
-	[ $UID -eq 0 ] && RERR "$LINENO" "Root access isn't required."
+	[ $UID -eq 0 ] && {
+		ERR "$LINENO" "Root access isn't required."
+	}
 	
 	declare -i DEPCOUNT=0
-	for DEP in /bin/{cat,grep,gzip} /usr/bin/{wget,dos2unix,uniq,sort,tr}
-	{
+	for DEP in /bin/{grep,gzip} /usr/bin/{wget,dos2unix,uniq,sort,tr}; {
 		[ -x "$DEP" ] || {
 			ERR "$LINENO" "Dependency '$DEP' not met."
 			DEPCOUNT+=1
@@ -27,18 +27,27 @@ gbh(){
 	
 	[ $DEPCOUNT -eq 0 ] || return 1
 
-	[ $# -eq 0 ] || RERR "$LINENO" "No arguments required."
+	[ $# -eq 0 ] || {
+		ERR "$LINENO" "No arguments required."
+		return 1
+	}
 
 	URL="http://www.montanamenagerie.org/hostsfile/hosts.txt"
 	DESTINATION="$HOME/Downloads/GBH.txt"
 
-	[ -d "${DESTINATION%\/*}" ] || RERR "$LINENO" "Destination directory not found."
-	[ -f "${DESTINATION}.gz" ] && RERR "$LINENO" "File already present."
+	[ -d "${DESTINATION%\/*}" ] || {
+		RERR "$LINENO" "Destination directory not found."
+		return 1
+	}
+
+	[ -f "${DESTINATION}.gz" ] && {
+		RERR "$LINENO" "File already present."
+		return 1
+	}
 
 	/usr/bin/wget -q --show-progress "$URL" -O "$DESTINATION"
 	/usr/bin/dos2unix "$DESTINATION"
 
-	#TODO - Check using while read rather than cat didn't break this.
 	while read -r; do
 		echo "$REPLY"
 	done <<< "$DESTINATION"\
