Updated Load_File_Links2; optimized

diff --git a/ShellPlugins/Load_File_Links2 b/ShellPlugins/Load_File_Links2
--- a/ShellPlugins/Load_File_Links2
+++ b/ShellPlugins/Load_File_Links2
@@ -3,30 +3,25 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Load_File_Links2
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Fri 13 Oct 23:51:50 BST 2017
+# Last Change       - Thu  8 Mar 05:42:24 GMT 2018
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 l2f(){
-	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
+	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
 
-	[ $UID -eq 0 ] && {
-		ERR "$LINENO" "Root access isn't recommended."
-		return 1
-	}
-
-	[ $# -gt 0 ] || {
+	if ! [ $# -gt 0 ]; then
 		ERR "$LINENO" "Please specify a file to be read."
 		return 1
-	}
-
-	[ -x /usr/bin/links2 ] && {
-		/usr/bin/links2 -force-html file://"$*"
-	} || {
-		ERR "$LINENO" "Dependency '/usr/bin/links2' not found."
-		return 1
-	}
+	else
+		if [ -x /usr/bin/links2 ]; then
+			/usr/bin/links2 -force-html file://"$*"
+		else
+			ERR "$LINENO" "Dependency '/usr/bin/links2' not found."
+			return 1
+		fi
+	fi
 }
 
 # vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
