Updated Play_Download_MPSYT; optimized

diff --git a/ShellPlugins/Play_Download_MPSYT b/ShellPlugins/Play_Download_MPSYT
--- a/ShellPlugins/Play_Download_MPSYT
+++ b/ShellPlugins/Play_Download_MPSYT
@@ -3,24 +3,19 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/ShellPlugins/Play_Download_MPSYT
 # Started On        - Thu 14 Sep 20:10:21 BST 2017
-# Last Change       - Fri 13 Oct 23:54:57 BST 2017
+# Last Change       - Thu  8 Mar 05:31:11 GMT 2018
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
 yt(){
 	ARG_FAIL(){ echo "USAGE: yt [-p|-d] URL" 1>&2; }
-	ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }
+	ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }
 
-	[ $UID -eq 0 ] && {
-		ERR "$LINENO" "Root access isn't required."
-		return 1
-	}
-
-	[ $# -gt 1 ] || {
+	if ! [ $# -gt 1 ]; then
 		ERR "$LINENO" "Please specify a package name."
 		return 1
-	}
+	fi
 
 	declare -i DEPCOUNT=0
 	for DEP in /usr/bin/{apt-get,awk,dpkg-query}; {
@@ -29,7 +24,7 @@ yt(){
 			DEPCOUNT+=1
 		}
 	}
-	
+
 	[ $DEPCOUNT -eq 0 ] || exit 1
 
 	if [ $# -gt 2 ]; then
