Remove libtflbp-sh from lad, & add nonroots alias

diff --git a/source/lad b/source/lad
--- a/source/lad
+++ b/source/lad
@@ -3,7 +3,7 @@
 #------------------------------------------------------------------------------
 # Project Name      - BashConfig/source/lad (List and Describe)
 # Started On        - Tue  9 Apr 14:48:44 BST 2019
-# Last Change       - Tue 20 Oct 22:39:44 BST 2020
+# Last Change       - Fri 13 Nov 03:30:45 GMT 2020
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
@@ -14,12 +14,7 @@
 #   libtflbp-sh (>= 2019-12-10)
 #------------------------------------------------------------------------------
 
-set -e
-. /usr/lib/tflbp-sh/Err
-. /usr/lib/tflbp-sh/ChkDep
-set +e
-
-CurVer='2020-10-20'
+CurVer='2020-11-13'
 Progrm=${0##*/}
 
 Usage(){
@@ -86,6 +81,11 @@ Usage(){
 	EOF
 }
 
+Err(){
+	printf 'ERROR: %s\n' "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
+}
+
 NL="\n"
 
 while [ "$1" ]; do
@@ -109,7 +109,7 @@ if [ -n "$OnlyFunc" -a -n "$OnlyAlias" ]; then
 	Err 1 "Either '--only-funcs|-F' or '--only-aliases|-A' may used at one time."
 fi
 
-ChkDep sort
+type -fP sort &> /dev/null || Err 1 "Dependency 'sort' not met."
 
 FileBF="$HOME/.bash_functions"
 FileBA="$HOME/.bash_aliases"
